---
- name: Install Elastick stack
  hosts: all
  become: true

  roles:
    - role: robertdebock.locale
    - role: geerlingguy.java
    - role: geerlingguy.elasticsearch
    - role: geerlingguy.logstash
    - role: geerlingguy.kibana
