---
jobs:
  molecule:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    parameters:
      molecule-image:
        type: string
    steps:
      - checkout
      - run:
          name: Install Molecule and dependencies
          command: |
            pip3 install -r molecule/requirements/docker
      - run:
          name: Test with Molecule
          command: |
            molecule test --scenario-name docker
          environment:
            PY_COLORS: '1'
            ANSIBLE_FORCE_COLOR: '1'
            MOLECULE_IMAGE: << parameters.molecule-image >>
      - run:
          name: Show Ansible version
          command: |
            pip3 list | grep ansible \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
      - run:
          name: Show Molecule version
          command: molecule --version

version: 2.1
workflows:
  version: 2
  build:
    jobs:
      - molecule:
          matrix:
            parameters:
              molecule-image:
                - 'ghcr.io/docker-hub-tm/ansible-test/centos7:latest'
                - 'ghcr.io/docker-hub-tm/ansible-test/centos-stream8:latest'
